### ISSUE TITLE
Add bias measurements

### ISSUE THREAD

**Issue by saattrupdan** [alexandrainst/AlexandraAI-eval#42]
We would like to add bias measurements to the evaluation framework.

We have to investigate what sort of metric(s) we want to use - it might involve curating a dataset for it.

**Comment by saattrupdan** [comment]
![IMG_0477-min](https://user-images.githubusercontent.com/47701536/191917456-07f0738b-ecc9-446c-b7fa-f3105d5ee346.png)

**Comment by AJDERS** [comment]
This has been split into different issues for different supertasks.
