### ISSUE TITLE
[FEATURE-REQUEST] Leaderboard

### ISSUE THREAD

**Issue by saattrupdan** [alexandrainst/AlexandraAI-eval#77]
**Is your feature request related to a problem? Please describe.**
We would like to connect the evaluation pipeline to a leaderboard, ideally updating the leaderboard automatically when the evaluation is run.

**Describe the solution you'd like**
The leaderboard could be hosted in a database, which a web service could tap into to display it on a website. When evaluating it could then be possible to update the leaderboard by providing credentials through the CLI or `Evaluator` initialiser.

**Describe alternatives you've considered**
We could also simply update the leaderboard manually, which might be doable since there aren't that many models to evaluate. An alternative to a database could also simply be a local JSON-style file here in the repo, which a web service could still tap into.

**Comment by AJDERS** [comment]
An MVP is now live at: [Link](https://api.aiai.alexandrainst.dk/web)
For more information see corresponding [repo](https://github.com/alexandrainst/AIAI-eval-leaderboard)

**Comment by AJDERS** [comment]
#106 MVP is use as outset for production ready frontend.
