### ISSUE TITLE
[BUG] `poetry install` hangs.

### ISSUE THREAD

**Issue by AJDERS** [alexandrainst/AlexandraAI-eval#84]
**Describe the bug**
`poetry install` hangs when making a clean install. 

```
anders_jess@blackknight:~/AIAI-eval$ poetry install
Installing dependencies from lock file

Package operations: 133 installs, 1 update, 0 removals

  • Installing catalogue (2.0.8): Pending...
  • Installing frozenlist (1.3.1): Pending...
  • Installing idna (3.4): Pending...
  • Installing mdurl (0.1.2): Pending...
  • Installing multidict (6.0.2): Pending...
  • Installing pycparser (2.21): Pending...
  • Installing pyparsing (3.0.9): Pending...
  • Installing sniffio (1.3.0): Pending...
  • Installing typing-extensions (4.3.0): Pending...
^C^C^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
Had hung for 15 min.

**To Reproduce**
`poetry install`

**Expected behaviour**
That all the packages are installed.

**Context (please complete the following information):**
 - OS [e.g., MacOS, Ubuntu]: Ubuntu
 - Python version [e.g., 3.10.6]: 3.8.10
 - Package version [e.g., 0.1.2]: 1.2.0

**Additional context**
[This](https://github.com/python-poetry/poetry/issues/3352#issuecomment-1254130692) might be a work-around, with the possible [caveat](https://github.com/python-poetry/poetry/issues/2094#issuecomment-1231501255).

**Comment by AJDERS** [comment]
The workaround did work!

**Comment by RamakrishnaHande** [comment]
hi @AJDERS  could you please give workaround ? I see this is happening inside my alpine image, but works fine in mac

**Comment by m-rav** [comment]
I was having this same issue and the keyring solution fixed it:

https://github.com/python-poetry/poetry/issues/6354
